In [1]:
from transform import transform_trafficData, transform_weatherData, get_y

/Users/hadoop1/anaconda/lib/python2.7/site-packages/pandas/computation/__init__.py:19: UserWarning: The installed version of numexpr 2.4.4 is not supported in pandas and will be not be used

  UserWarning)

In [2]:
date = '2016-01-10'

In [3]:
transform_trafficData(date, folder='training')

KeyError: 'time_slot'

In [2]:
from transform import create_matrix

In [1]:
from transform import get_y

/Users/hadoop1/anaconda/lib/python2.7/site-packages/pandas/computation/__init__.py:19: UserWarning: The installed version of numexpr 2.4.4 is not supported in pandas and will be not be used

  UserWarning)

In [2]:
from transform import transform_trafficData

In [1]:
from transform import transform_weatherData

In [3]:
transform_weatherData('2016-01-21', folder='training')

transform.py:85: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  weatherDropDf['date'] = date

           Weather  temperature  PM25  slot        date
time_slot
43               4          1.0    49    43  2016-01-21
44               4          1.0    49    44  2016-01-21
46               4          1.0    49    46  2016-01-21
48               4          1.0    50    48  2016-01-21
50               4          1.0    50    50  2016-01-21
54               4          1.0    49    54  2016-01-21
57               4          1.0    49    57  2016-01-21
59               4          1.0    49    59  2016-01-21
115              4          1.0    44   115  2016-01-21
117              4          1.0    44   117  2016-01-21
118              4          2.0    44   118  2016-01-21
119              4          1.0    48   119  2016-01-21
120              4          1.0    48   120  2016-01-21
121              4          1.0    48   121  2016-01-21
122              4          1.0    48   122  2016-01-21
123              2          1.0    48   123  2016-01-21
124              2          1.0    48   124  2016-01-21
125              2          1.0    53   125  2016-01-21
126              2          1.0    53   126  2016-01-21
127              2          1.0    53   127  2016-01-21
128              2          1.0    53   128  2016-01-21
129              2          1.0    53   129  2016-01-21
130              2          1.0    53   130  2016-01-21
131              2          1.0    53   131  2016-01-21
132              2          1.0    53   132  2016-01-21
133              2          1.0    53   133  2016-01-21
134              2          1.0    53   134  2016-01-21
135              2          1.0    53   135  2016-01-21
136              2          1.0    58   136  2016-01-21
137              2          1.0    58   137  2016-01-21
138              2          1.0    58   138  2016-01-21
139              2          1.0    58   139  2016-01-21
140              2          1.0    58   140  2016-01-21
141              2          1.0    58   141  2016-01-21
142              2          1.0    58   142  2016-01-21
143              2          1.0    59   143  2016-01-21
144              2          1.0    59   144  2016-01-21

In [5]:
transform_trafficData('2016-01-22', folder='testing')

,district_id,traffic_level1,traffic_level2,traffic_level3,traffic_level4
time_slot,,,,,
2016-01-22-56,66,239,127,28,21
2016-01-22-105,2,627,299,55,22
2016-01-22-57,2,660,143,18,19
2016-01-22-79,5,90,28,5,0
2016-01-22-68,6,301,53,19,19
2016-01-22-91,41,303,39,23,0
2016-01-22-129,49,234,41,0,4
2016-01-22-80,49,224,29,9,3
2016-01-22-116,38,405,113,43,28
2016-01-22-67,43,153,14,1,1
2016-01-22-103,10,164,29,2,5
2016-01-22-127,14,1511,302,71,62
2016-01-22-55,17,368,29,14,9
2016-01-22-115,12,1734,422,101,56
2016-01-22-104,19,1145,207,90,48
2016-01-22-141,57,529,44,18,16
2016-01-22-67,53,371,73,9,5
2016-01-22-56,35,301,75,27,22
2016-01-22-45,7,1864,252,75,56
2016-01-22-104,48,2543,873,263,135
2016-01-22-55,24,1138,270,99,45
2016-01-22-44,58,117,17,4,3
2016-01-22-128,50,189,32,3,0
2016-01-22-139,60,150,21,1,0
2016-01-22-127,34,237,49,6,2
2016-01-22-80,34,252,50,16,10
2016-01-22-67,1,1709,355,66,111
2016-01-22-56,29,782,171,26,30
2016-01-22-127,22,705,152,39,21
2016-01-22-80,22,785,198,50,32
...,...,...,...,...,...
2016-01-22-67,32,127,26,4,2
2016-01-22-141,66,193,20,16,20
2016-01-22-55,66,256,94,22,21
2016-01-22-104,2,626,301,44,26
2016-01-22-56,2,688,142,40,27
2016-01-22-117,5,135,10,2,9
2016-01-22-67,6,302,58,16,27
2016-01-22-45,41,299,41,9,6
2016-01-22-128,49,291,29,5,2
2016-01-22-115,38,423,116,53,15
2016-01-22-139,10,153,13,9,0
2016-01-22-103,19,1074,202,66,32
2016-01-22-93,19,1015,141,38,54
2016-01-22-140,57,541,41,17,18
2016-01-22-129,35,305,33,8,4
2016-01-22-55,35,288,52,14,2
2016-01-22-105,52,200,19,3,2
2016-01-22-44,7,1770,283,71,38
2016-01-22-103,48,2651,803,271,124
2016-01-22-93,48,2564,742,230,160
2016-01-22-43,58,124,18,3,2
2016-01-22-127,50,140,41,10,3
2016-01-22-81,61,83,65,14,2
2016-01-22-105,45,224,20,4,1
2016-01-22-129,29,822,196,37,23
2016-01-22-55,29,768,144,43,14
2016-01-22-105,62,38,7,2,3
2016-01-22-79,27,1439,310,47,41
2016-01-22-141,32,129,7,6,0
2016-01-22-68,32,119,9,4,0

In [6]:
testDf

NameError: name 'testDf' is not defined

In [7]:
from transform import transform_weatherData

In [8]:
weatherDf = transform_weatherData('2016-01-21', folder='training')

In [9]:
%matplotlib inline